// AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
// OKLCH design tokens converted to static sRGB hex for React Native.

export type EditionName = 'Ink & Gold' | 'Oxblood & Bronze' | 'Verdigris & Brass';

export type Palette = {
  bg0: string; bg1: string; bg2: string;
  line: string; lineStrong: string;
  ink: string; mute: string; faint: string;
  accent: string; gold: string; glow: string; star: string;
  surface: string; textareaBg: string; lineHalf: string; goldTint: string; inkBorder: string;
  moonLit: string[]; moonPlateLit: string[];
  moonDark: string; moonPlateDark: string;
  onGold: string; onGoldBtn: string; vignette: string;
  bodyBgTop: string; bodyBgBot: string;
};

export const EDITIONS: Record<EditionName, Palette> = {
  "Ink & Gold": {
    "bg0": "#070c18",
    "bg1": "#0d1220",
    "bg2": "#161b2b",
    "line": "#d9b97957",
    "lineStrong": "#d9b9799e",
    "ink": "#eee7d8",
    "mute": "#bbaf9c",
    "faint": "#8c7e69",
    "accent": "#dfbc73",
    "gold": "#e4c379",
    "glow": "#dfbc734d",
    "star": "#e6d6b3",
    "surface": "#0d1220e0",
    "textareaBg": "#0d1220b3",
    "lineHalf": "#d9b9792b",
    "goldTint": "#e4c37921",
    "inkBorder": "#eee7d84d",
    "moonLit": [
      "#e3b58d",
      "#e6b59a",
      "#e9b8a9",
      "#c3d5c3",
      "#cdddba",
      "#dce1b5",
      "#f1dfb6"
    ],
    "moonPlateLit": [
      "#e2ae86",
      "#e5af95",
      "#e8b2a7",
      "#bdd3c2",
      "#c8dcb8",
      "#d8e0b2",
      "#f1deb2"
    ],
    "moonDark": "#04050de6",
    "moonPlateDark": "#04050d",
    "onGold": "#181003",
    "onGoldBtn": "#160e02",
    "vignette": "#02030999",
    "bodyBgTop": "#0d1220",
    "bodyBgBot": "#020307"
  },
  "Oxblood & Bronze": {
    "bg0": "#190606",
    "bg1": "#210b0b",
    "bg2": "#2c1413",
    "line": "#cd97765c",
    "lineStrong": "#cd9776a3",
    "ink": "#f2e1d4",
    "mute": "#c1a89b",
    "faint": "#987466",
    "accent": "#dea279",
    "gold": "#e6ad7f",
    "glow": "#dea2794d",
    "star": "#e6c7ad",
    "surface": "#210b0be0",
    "textareaBg": "#210b0bb3",
    "lineHalf": "#cd97762e",
    "goldTint": "#e6ad7f21",
    "inkBorder": "#f2e1d44d",
    "moonLit": [
      "#e8ae94",
      "#e9b0a1",
      "#e9b3b1",
      "#e1c4cd",
      "#d5d8b1",
      "#e5dbae",
      "#f8d9b5"
    ],
    "moonPlateLit": [
      "#e7a88e",
      "#e7aa9d",
      "#e7aeb0",
      "#dec2cd",
      "#d0d7af",
      "#e2daab",
      "#f9d8b1"
    ],
    "moonDark": "#04050de6",
    "moonPlateDark": "#04050d",
    "onGold": "#181003",
    "onGoldBtn": "#160e02",
    "vignette": "#02030999",
    "bodyBgTop": "#0d1220",
    "bodyBgBot": "#020307"
  },
  "Verdigris & Brass": {
    "bg0": "#000f10",
    "bg1": "#011617",
    "bg2": "#051f21",
    "line": "#bcbc7f57",
    "lineStrong": "#bcbc7f9e",
    "ink": "#e6eada",
    "mute": "#abb5a1",
    "faint": "#6d8471",
    "accent": "#c1c37e",
    "gold": "#c7ca85",
    "glow": "#c1c37e4d",
    "star": "#d0dab5",
    "surface": "#011617e0",
    "textareaBg": "#011617b3",
    "lineHalf": "#bcbc7f2b",
    "goldTint": "#c7ca8521",
    "inkBorder": "#e6eada4d",
    "moonLit": [
      "#d7bb87",
      "#ddbb91",
      "#e3bc9e",
      "#bcd6cb",
      "#c0e0c4",
      "#cde5bf",
      "#e3e5b9"
    ],
    "moonPlateLit": [
      "#d7b57e",
      "#ddb58a",
      "#e4b69a",
      "#b8d4ca",
      "#bbdfc3",
      "#c9e5bd",
      "#e3e4b5"
    ],
    "moonDark": "#04050de6",
    "moonPlateDark": "#04050d",
    "onGold": "#181003",
    "onGoldBtn": "#160e02",
    "vignette": "#02030999",
    "bodyBgTop": "#0d1220",
    "bodyBgBot": "#020307"
  }
} as const;

export const EDITION_NAMES = ["Ink & Gold","Oxblood & Bronze","Verdigris & Brass"] as const;

export type Mood = { key: string; label: string; short: string; color: string; pillTint: string; moon: number };

export const MOODS: Mood[] = [
  {
    "key": "nightmare",
    "label": "Nightmare",
    "short": "Terror",
    "color": "#cb4453",
    "moon": 0,
    "pillTint": "#cb445338"
  },
  {
    "key": "troubling",
    "label": "Troubling",
    "short": "Dread",
    "color": "#c0558d",
    "moon": 0.18,
    "pillTint": "#c0558d38"
  },
  {
    "key": "restless",
    "label": "Restless",
    "short": "Unease",
    "color": "#a370c2",
    "moon": 0.36,
    "pillTint": "#a370c238"
  },
  {
    "key": "hazy",
    "label": "Hazy",
    "short": "Neutral",
    "color": "#8da8c3",
    "moon": 0.5,
    "pillTint": "#8da8c338"
  },
  {
    "key": "tender",
    "label": "Tender",
    "short": "Calm",
    "color": "#5dcbd1",
    "moon": 0.66,
    "pillTint": "#5dcbd138"
  },
  {
    "key": "wondrous",
    "label": "Wondrous",
    "short": "Awe",
    "color": "#7bdfac",
    "moon": 0.84,
    "pillTint": "#7bdfac38"
  },
  {
    "key": "blissful",
    "label": "Blissful",
    "short": "Rapture",
    "color": "#f3d173",
    "moon": 1,
    "pillTint": "#f3d17338"
  }
];

export const moodOf = (i: number): Mood => MOODS[Math.max(0, Math.min(6, i))];
